package DHMSApp;


/**
* DHMSApp/DHMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DHMS.idl
* Friday, March 1, 2024 8:41:16 PM EST
*/

public interface DHMS extends DHMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DHMS
