package DHMSApp;


/**
* DHMSApp/DHMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DHMS.idl
* Tuesday, February 27, 2024 4:07:23 PM EST
*/

public interface DHMS extends DHMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DHMS
