package DHMSApp;


/**
* DHMSApp/DHMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DHMS.idl
* Friday, March 1, 2024 8:41:16 PM EST
*/

public abstract class DHMSPOA extends org.omg.PortableServer.Servant
 implements DHMSApp.DHMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hello", new java.lang.Integer (0));
    _methods.put ("addAppointment", new java.lang.Integer (1));
    _methods.put ("removeAppointment", new java.lang.Integer (2));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (3));
    _methods.put ("bookAppointment", new java.lang.Integer (4));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (5));
    _methods.put ("cancelAppointment", new java.lang.Integer (6));
    _methods.put ("swapAppointment", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DHMSApp/DHMS/hello
       {
         String $result = null;
         $result = this.hello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DHMSApp/DHMS/addAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addAppointment (appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DHMSApp/DHMS/removeAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DHMSApp/DHMS/listAppointmentAvailability
       {
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DHMSApp/DHMS/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DHMSApp/DHMS/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DHMSApp/DHMS/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DHMSApp/DHMS/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DHMSApp/DHMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DHMS _this() 
  {
    return DHMSHelper.narrow(
    super._this_object());
  }

  public DHMS _this(org.omg.CORBA.ORB orb) 
  {
    return DHMSHelper.narrow(
    super._this_object(orb));
  }


} // class DHMSPOA
