package DHMSApp;


/**
* DHMSApp/DHMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DHMS.idl
* Tuesday, February 27, 2024 5:34:38 PM EST
*/

public interface DHMSOperations 
{
  String hello ();
  String addAppointment (String appointmentID, String appointmentType, int capacity);
  String removeAppointment (String appointmentID, String appointmentType);
  String listAppointmentAvailability (String appointmentType);
  String bookAppointment (String patientID, String appointmentID, String appointmentType);
  String getAppointmentSchedule (String patientID);
  String cancelAppointment (String patientID, String appointmentID);
  String swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType);
} // interface DHMSOperations
