package DHMSApp;


/**
* DHMSApp/DHMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DHMS.idl
* Saturday, March 2, 2024 12:02:13 PM EST
*/

public interface DHMS extends DHMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DHMS
